// src/harvester/mappings/met-taxonomy.ts
// ⚠️ GOLDEN RULE 2: CONFIG-DRIVEN MAPPER
// No if/else logic. Just data dictionaries.

export interface TaxonomyRule {
  subCategory: string;
  score: number;
}

export const MET_TAXONOMY = {
  graphicDesign: {
    departmentIds: [9],
    objectNameScores: {
      'Poster':             { subCategory: 'Posters & Advertising',  score: 20 },
      'Advertisement':      { subCategory: 'Posters & Advertising',  score: 18 },
      'Trade card':         { subCategory: 'Posters & Advertising',  score: 16 },
      'Ephemera':           { subCategory: 'Posters & Advertising',  score: 12 },
      'Commercial art':     { subCategory: 'Posters & Advertising',  score: 14 },
      'Broadside':          { subCategory: 'Posters & Advertising',  score: 14 },
      'Handbill':           { subCategory: 'Posters & Advertising',  score: 14 },
      'Flyer':              { subCategory: 'Posters & Advertising',  score: 12 },
      'Specimen':           { subCategory: 'Typography & Lettering', score: 18 },
      'Lettering':          { subCategory: 'Typography & Lettering', score: 20 },
      'Alphabet':           { subCategory: 'Typography & Lettering', score: 16 },
      'Type specimen':      { subCategory: 'Typography & Lettering', score: 22 },
      'Typeface':           { subCategory: 'Typography & Lettering', score: 20 },
      'Trademark':          { subCategory: 'Identity & Branding',    score: 18 },
      'Logo':               { subCategory: 'Identity & Branding',    score: 20 },
      'Book jacket':        { subCategory: 'Editorial/Publication',  score: 18 },
      'Magazine cover':     { subCategory: 'Editorial/Publication',  score: 18 },
      'Book cover':         { subCategory: 'Editorial/Publication',  score: 16 },
      'Label':              { subCategory: 'Packaging',              score: 16 },
      'Packaging':          { subCategory: 'Packaging',              score: 18 },
      'Wrapper':            { subCategory: 'Packaging',              score: 14 },
    } as Record<string, TaxonomyRule>,
    classificationScores: {
      'Commercial Art':       10,
      'Visual Communication': 10,
      'Graphic Design':       12,
      'Print Ephemera':        8,
      'Typography':           10,
    } as Record<string, number>,
    mediumScores: {
      'Lithograph':        6,
      'Chromolithograph':  8,
      'Screenprint':       6,
      'Offset lithograph': 6,
      'Serigraph':         6,
      'Letterpress':       8,
    } as Record<string, number>,
    defaultSubCategory: 'Posters & Advertising',
    excludeObjectNames: ['Painting', 'Sculpture', 'Drawing', 'Print'],
    excludeClassifications: ['Paintings', 'Sculpture', 'Drawings', 'Prints'],
  },

  painting: {
    departmentIds: [11, 21],
    objectNameScores: {
      'Painting':       { subCategory: 'Oil',                 score: 18 },
      'Panel painting': { subCategory: 'Oil',                 score: 16 },
      'Miniature':      { subCategory: 'Watercolor/Gouache',  score: 14 },
      'Portrait':       { subCategory: 'Oil',                 score: 12 },
      'Landscape':      { subCategory: 'Oil',                 score: 12 },
    } as Record<string, TaxonomyRule>,
    classificationScores: {
      'Paintings': 12,
      'Painting':  10,
    } as Record<string, number>,
    mediumScores: {
      'Oil on canvas':  20,
      'Oil on panel':   18,
      'Oil on wood':    18,
      'Oil on copper':  18,
      'Watercolor':     16,
      'Watercolour':    16,
      'Gouache':        14,
      'Tempera':        14,
      'Fresco':         12,
    } as Record<string, number>,
    defaultSubCategory: 'Oil',
    excludeObjectNames: ['Print', 'Drawing', 'Poster', 'Photograph'],
    excludeClassifications: ['Prints', 'Drawings', 'Photographs', 'Commercial Art'],
  },

  printsDrawings: {
    departmentIds: [9],
    objectNameScores: {
      // Intaglio prints
      'Print':          { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      'Etching':        { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Engraving':      { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Aquatint':       { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Mezzotint':      { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Drypoint':       { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Intaglio':       { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      // Relief prints
      'Woodcut':        { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Wood engraving': { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Woodblock':      { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Linocut':        { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      'Linoleum cut':   { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      'Relief print':   { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      // Planographic
      'Lithograph':     { subCategory: 'Etching/Woodcut/Lithograph', score: 20 },
      'Screenprint':    { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      'Silkscreen':     { subCategory: 'Etching/Woodcut/Lithograph', score: 18 },
      'Monotype':       { subCategory: 'Etching/Woodcut/Lithograph', score: 16 },
      // Drawings
      'Drawing':        { subCategory: 'Drawings', score: 18 },
      'Sketch':         { subCategory: 'Drawings', score: 16 },
      'Study':          { subCategory: 'Drawings', score: 14 },
      'Watercolor':     { subCategory: 'Drawings', score: 16 },
      'Gouache':        { subCategory: 'Drawings', score: 14 },
      'Pastel':         { subCategory: 'Drawings', score: 14 },
      'Charcoal':       { subCategory: 'Drawings', score: 14 },
      'Chalk':          { subCategory: 'Drawings', score: 12 },
      // Other
      'Collage':        { subCategory: 'Collage',  score: 18 },
      'Album':          { subCategory: 'Etching/Woodcut/Lithograph', score: 12 },
    } as Record<string, TaxonomyRule>,
    classificationScores: {
      'Prints':      12,
      'Drawings':    12,
      'Printmaking': 10,
      'Graphic Arts': 8,
    } as Record<string, number>,
    mediumScores: {
      'Etching':     18,
      'Engraving':   16,
      'Lithograph':  18,
      'Woodcut':     18,
      'Screenprint': 14,
      'Collage':     16,
      'Aquatint':    18,
      'Mezzotint':   18,
      'Drypoint':    18,
    } as Record<string, number>,
    defaultSubCategory: 'Etching/Woodcut/Lithograph',
    excludeObjectNames: ['Painting', 'Poster', 'Photograph'],
    excludeClassifications: ['Paintings', 'Commercial Art', 'Photographs'],
  },

  photography: {
    departmentIds: [19],
    objectNameScores: {
      'Photograph':         { subCategory: 'Photograph', score: 20 },
      'Photo':              { subCategory: 'Photograph', score: 18 },
      'Portrait photograph':{ subCategory: 'Photograph', score: 16 },
      'Daguerreotype':      { subCategory: 'Photograph', score: 22 },
      'Tintype':            { subCategory: 'Photograph', score: 20 },
      'Ambrotype':          { subCategory: 'Photograph', score: 20 },
      'Calotype':           { subCategory: 'Photograph', score: 20 },
      'Cyanotype':          { subCategory: 'Photograph', score: 20 },
      'Photomontage':       { subCategory: 'Photograph', score: 18 },
      'Photogram':          { subCategory: 'Photograph', score: 18 },
      'Photoprint':         { subCategory: 'Photograph', score: 18 },
      'Stereograph':        { subCategory: 'Photograph', score: 16 },
      'Albumen print':      { subCategory: 'Photograph', score: 18 },
      'Gelatin silver print':{ subCategory: 'Photograph', score: 18 },
    } as Record<string, TaxonomyRule>,
    classificationScores: {
      'Photographs': 12,
      'Photography': 10,
    } as Record<string, number>,
    mediumScores: {
      'Gelatin silver print': 20,
      'Albumen print':        18,
      'Cyanotype':            18,
      'Daguerreotype':        22,
      'Tintype':              20,
      'Platinum print':       18,
      'Photogravure':         16,
      'Ambrotype':            18,
      'Salted paper print':   16,
    } as Record<string, number>,
    defaultSubCategory: 'Photograph',
    excludeObjectNames: ['Painting', 'Print', 'Drawing'],
    excludeClassifications: ['Paintings', 'Prints', 'Drawings', 'Commercial Art'],
  },

  decorativeArts: {
    departmentIds: [1, 12],
    objectNameScores: {
      // Ceramics & Glass
      'Vase':          { subCategory: 'Ceramics & Glass',    score: 16 },
      'Bowl':          { subCategory: 'Ceramics & Glass',    score: 14 },
      'Plate':         { subCategory: 'Ceramics & Glass',    score: 14 },
      'Cup':           { subCategory: 'Ceramics & Glass',    score: 12 },
      'Jug':           { subCategory: 'Ceramics & Glass',    score: 12 },
      'Jar':           { subCategory: 'Ceramics & Glass',    score: 12 },
      'Porcelain':     { subCategory: 'Ceramics & Glass',    score: 18 },
      'Ceramic':       { subCategory: 'Ceramics & Glass',    score: 16 },
      'Glass':         { subCategory: 'Ceramics & Glass',    score: 16 },
      'Bottle':        { subCategory: 'Ceramics & Glass',    score: 12 },
      // Furniture
      'Chair':         { subCategory: 'Furniture',           score: 16 },
      'Table':         { subCategory: 'Furniture',           score: 16 },
      'Cabinet':       { subCategory: 'Furniture',           score: 16 },
      'Desk':          { subCategory: 'Furniture',           score: 14 },
      'Chest':         { subCategory: 'Furniture',           score: 14 },
      'Bed':           { subCategory: 'Furniture',           score: 14 },
      'Clock':         { subCategory: 'Furniture',           score: 12 },
      // Textiles
      'Dress':         { subCategory: 'Textiles & Fashion',  score: 16 },
      'Textile':       { subCategory: 'Textiles & Fashion',  score: 18 },
      'Tapestry':      { subCategory: 'Textiles & Fashion',  score: 18 },
      'Costume':       { subCategory: 'Textiles & Fashion',  score: 16 },
      'Lace':          { subCategory: 'Textiles & Fashion',  score: 14 },
      'Embroidery':    { subCategory: 'Textiles & Fashion',  score: 16 },
      'Rug':           { subCategory: 'Textiles & Fashion',  score: 14 },
      // Metalwork
      'Necklace':      { subCategory: 'Metalwork & Jewelry', score: 16 },
      'Silver':        { subCategory: 'Metalwork & Jewelry', score: 18 },
      'Metalwork':     { subCategory: 'Metalwork & Jewelry', score: 16 },
      'Brooch':        { subCategory: 'Metalwork & Jewelry', score: 16 },
      'Ring':          { subCategory: 'Metalwork & Jewelry', score: 14 },
      'Bracelet':      { subCategory: 'Metalwork & Jewelry', score: 14 },
      'Pendant':       { subCategory: 'Metalwork & Jewelry', score: 14 },
      'Spoon':         { subCategory: 'Metalwork & Jewelry', score: 12 },
    } as Record<string, TaxonomyRule>,
    classificationScores: {
      'Ceramics':   12,
      'Glass':      12,
      'Furniture':  12,
      'Textiles':   12,
      'Costume':    12,
      'Metalwork':  12,
      'Jewelry':    12,
    } as Record<string, number>,
    defaultSubCategory: 'Ceramics & Glass',
    excludeObjectNames: ['Painting', 'Print', 'Drawing', 'Photograph', 'Poster'],
    excludeClassifications: ['Paintings', 'Prints', 'Drawings', 'Photographs', 'Commercial Art'],
  },
} as const;

export type MetCategory = keyof typeof MET_TAXONOMY;